"""initial schema

Revision ID: 677311f11ba0
Revises: 
Create Date: 2026-06-05 23:19:13.273093

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677311f11ba0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bracket_slots',
    sa.Column('match_number', sa.SmallInteger(), nullable=False),
    sa.Column('stage', sa.String(length=8), nullable=False),
    sa.Column('home_source', sa.String(length=8), nullable=False),
    sa.Column('away_source', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('match_number')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('fifa_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_number')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('position', sa.String(length=2), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions_bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.SmallInteger(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['match_number'], ['bracket_slots.match_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_number')
    )
    op.create_index(op.f('ix_predictions_bracket_match_number'), 'predictions_bracket', ['match_number'], unique=False)
    op.create_index(op.f('ix_predictions_bracket_user_id'), 'predictions_bracket', ['user_id'], unique=False)
    op.create_table('predictions_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('award_type', sa.String(length=24), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'award_type')
    )
    op.create_index(op.f('ix_predictions_awards_user_id'), 'predictions_awards', ['user_id'], unique=False)
    op.create_table('predictions_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_match_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=False),
    sa.Column('away_score', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_match_id'], ['group_matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_match_id')
    )
    op.create_index(op.f('ix_predictions_group_user_id'), 'predictions_group', ['user_id'], unique=False)
    op.create_table('predictions_tot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=2), nullable=False),
    sa.Column('slot_index', sa.SmallInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'player_id'),
    sa.UniqueConstraint('user_id', 'position', 'slot_index')
    )
    op.create_index(op.f('ix_predictions_tot_user_id'), 'predictions_tot', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_tot_user_id'), table_name='predictions_tot')
    op.drop_table('predictions_tot')
    op.drop_index(op.f('ix_predictions_group_user_id'), table_name='predictions_group')
    op.drop_table('predictions_group')
    op.drop_index(op.f('ix_predictions_awards_user_id'), table_name='predictions_awards')
    op.drop_table('predictions_awards')
    op.drop_index(op.f('ix_predictions_bracket_user_id'), table_name='predictions_bracket')
    op.drop_index(op.f('ix_predictions_bracket_match_number'), table_name='predictions_bracket')
    op.drop_table('predictions_bracket')
    op.drop_table('players')
    op.drop_table('group_matches')
    op.drop_table('teams')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('bracket_slots')
    # ### end Alembic commands ###
